# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import raft_pb2 as raft__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in raft_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RaftNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ackHeartbeat = channel.unary_unary(
                '/RaftNode/ackHeartbeat',
                request_serializer=raft__pb2.heartbeatMessage.SerializeToString,
                response_deserializer=raft__pb2.ackMessage.FromString,
                _registered_method=True)
        self.logAppend = channel.unary_unary(
                '/RaftNode/logAppend',
                request_serializer=raft__pb2.logMessage.SerializeToString,
                response_deserializer=raft__pb2.ackMessage.FromString,
                _registered_method=True)


class RaftNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ackHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def logAppend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ackHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.ackHeartbeat,
                    request_deserializer=raft__pb2.heartbeatMessage.FromString,
                    response_serializer=raft__pb2.ackMessage.SerializeToString,
            ),
            'logAppend': grpc.unary_unary_rpc_method_handler(
                    servicer.logAppend,
                    request_deserializer=raft__pb2.logMessage.FromString,
                    response_serializer=raft__pb2.ackMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RaftNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RaftNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RaftNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ackHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RaftNode/ackHeartbeat',
            raft__pb2.heartbeatMessage.SerializeToString,
            raft__pb2.ackMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def logAppend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RaftNode/logAppend',
            raft__pb2.logMessage.SerializeToString,
            raft__pb2.ackMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
